# Generated by Django 5.2.3 on 2025-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cookingstep',
            constraint=models.UniqueConstraint(fields=('recipe', 'order'), name='unique_step_order_per_recipe'),
        ),
    ]
